version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
      include: 'scope'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'production'
